version: "3.9"

services:
  django:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - REDIS_URL=redis://redis:6379/1
      - DATABASE_URL=postgres://postgres:postgres@db:5432/spices_db
    depends_on:
      - redis
      - db
    networks:
      - spices-network

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    networks:
      - spices-network

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A spices_project worker --loglevel=info
    volumes:
      - .:/app
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - REDIS_URL=redis://redis:6379/1
      - DATABASE_URL=postgres://postgres:postgres@db:5432/spices_db
    depends_on:
      - redis
      - django
    networks:
      - spices-network
    restart: unless-stopped

  db:
    image: postgres:14
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=spices_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - spices-network

volumes:
  postgres_data:

networks:
  spices-network:
    driver: bridge
